spring.application.name=api-gateway
spring.cloud.gateway.server.webmvc.routes[0].id=restaurants_service
spring.cloud.gateway.server.webmvc.routes[0].uri=${RESTAURANTS_URI}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/restaurants/**
spring.cloud.gateway.server.webmvc.routes[1].id=users_service
spring.cloud.gateway.server.webmvc.routes[1].uri=${USERS_URI}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webmvc.routes[2].id=delivery_agents_service
spring.cloud.gateway.server.webmvc.routes[2].uri=${DELIVERY_AGENTS_URI}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/delivery-agents/**