spring.application.name=api-gateway
spring.cloud.gateway.server.webmvc.routes[0].id=restaurants_service
spring.cloud.gateway.server.webmvc.routes[0].uri=${HOST}:${RESTAURANTS_PORT}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/restaurants/**
spring.cloud.gateway.server.webmvc.routes[1].id=users_service
spring.cloud.gateway.server.webmvc.routes[1].uri=${HOST}:${USERS_PORT}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webmvc.routes[2].id=delivery_agents_service
spring.cloud.gateway.server.webmvc.routes[2].uri=${HOST}:${DELIVERY_AGENTS_PORT}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/delivery-agents/**